### ISSUE TITLE
telegram-desktop creates local .desktop file when running

### ISSUE THREAD

**Issue by isage** [RussianFedora/telegram-desktop#1]
Subj. This leads to duplicate entries in menu.
Moreover, it registers tg:// scheme handler, but only for gnome and kde4
See https://github.com/telegramdesktop/tdesktop/blob/4857135e4233912b2ea7378c7b28f2be9b1c3787/Telegram/SourceFiles/pspecific_linux.cpp#L1167

I know this is hard, but we really should build it from source.

**Comment by Tigro** [comment]
They say here https://github.com/telegramdesktop/tdesktop/blob/master/QTCREATOR.md to patch Qt. I know if any soft required patched Qt it won't be supported in Linux distributions.

**Comment by isage** [comment]
Yeah, well, currently shipped binaries still use custom-built patched Qt, statically linked.

**Comment by isage** [comment]
Or, maybe we can ask upstream to move custom-handler code to some wrapper script instead.

**Comment by Tigro** [comment]
I try to provide YaChat in Yandex what required patched Qt. That was the HELL. Nobody will support this. It's really too hard. It would be better if we will pack binaries.
